[package]
name = "apue"
version = "0.1.0"
authors = ["Shion Yamashita <shioyama1118@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.84"
num = "0.3.1"
errno = "0.2.7"

[[example]]
name = "f03_list_files"
path = "example/ch01_overview/f03_list_files.rs"

[[example]]
name = "f04_copy_stdin_stdout"
path = "example/ch01_overview/f04_copy_stdin_stdout.rs"

[[example]]
name = "f05_getc_putc"
path = "example/ch01_overview/f05_getc_putc.rs"

[[example]]
name = "f06_getpid"
path = "example/ch01_overview/f06_getpid.rs"
